      <div id="legFooter" class="leg-footer d-print-none position-relative">
        <footer class="footer bg-light">
          <div class="container" style="">
            <div class="row pt-3 px-4">            
              <div class="col-sm-6 col-md-3">
                <h5 class="title-widget text-left">About the Legislature</h5>
                <ul  class="list-unstyled clear-margins">
                  <li>
                    <a href="http://www.leg.state.mn.us/lrl/history/">Historical Information</a>
                  </li>
                  <li>
                    <a href="http://www.leg.state.mn.us/leg/jobs.aspx">Employment/Internships</a>
                  </li>
                  <li>
                    <a href="https://www.leg.state.mn.us/leg/faq/faq?subject=14">Visiting the Capitol</a>
                  </li>
                  <li>
                    <a href="https://www.leg.state.mn.us/leg/faq/faq?subject=19">Special Needs Access</a>
                  </li>
                  <li>
                    <a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx">Frequently Asked Questions</a>
                  </li>
                </ul>
              </div>
              <div class="col-sm-6 col-md-3">
                <h5 class="title-widget text-left">Contact Your Legislator</h5>
                <ul  class="list-unstyled clear-margins">
                  <li   class="mt-2"><a href="http://www.gis.leg.mn/OpenLayers/districts/">Who Represents Me?</a></li>
                  <li><a href="http://www.house.leg.state.mn.us/members/hmem.asp">House Members</a></li>
                  <li><a href="http://www.senate.leg.state.mn.us/members/index.php">Senators</a></li>
                </ul>
              </div>
              <div class="col-sm-6 col-md-3">
                <h5 class="title-widget text-left">General Contact</h5>
                <ul  class="list-unstyled clear-margins">
                  <li><a href="tel:651-296-0098">(651) 296-0098</a> or <a href="mailto:lcc@lcc.leg.mn">Email</a></li>
                  <li class="mt-2 mt-lg-0"><a href="https://ww2.gis.leg.mn/staff.html">Phone Numbers</a></li>
                    
                  <li><a href="mailto:gis@lcc.leg.mn">Submit website comments</a></li>            
                </ul>
              </div>
              <div class="col-sm-6 col-md-3">
                <h5 class="title-widget">Get Connected</h5>
                <ul class="list-unstyled clear-margins">
                  <li><a href="http://www.house.mn/hinfo/news.asp">House News</a></li>
                  <li><a href="http://www.senate.leg.state.mn.us/media/">Senate News</a></li>
                  <li><a href="http://www.leg.state.mn.us/mybills/">MyBills</a></li>
                  <li><a href="http://www.leg.state.mn.us/leg/elists.aspx">Email Updates &amp; RSS Feeds</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
        <div class="row">
          <div class="col-12 bg-dark">
            <div class="text-center text-light py-1 leg-subfooter">LCC - GIS &middot; 100 Rev. Dr. Martin Luther King Jr. Blvd. Saint Paul, MN 55155 &middot; <a href="mailto:gis@lcc.leg.mn">gis@lcc.leg.mn</a></div>
          </div>
        </div>
      </div>
    </div> <!-- container.fluid (from top) -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1837822423128844',
          xfbml      : true,
          version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-7370043-1', 'auto');
      ga('send', 'pageview');

    </script>
    <script src="https://ww2.gis.leg.mn/assets/js/jquery-ui-1.12.1.custom/jquery-ui.min.js">
    </script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js">
    </script> 
    <script src="https://ww2.gis.leg.mn/assets/node_modules/bootstrap/dist/js/bootstrap.min.js">
    </script> 
  </body>
</html>